import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '../components/header/header'
import AuthProvider from '@/context/AuthProvider'

import './globals.css'
import 'boxicons/css/boxicons.min.css'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
